version: '2.3'

services:

  osm2pgsql-updater:
    # continuously update from live OSM data to PostgresSQL (geoshapes)
    image: sophox/osm2pgsql_osmium
    command: /osm-to-pgsql/osm2pgsql-update.sh
    restart: on-failure
    volumes:
    - "${STATUS_DIR}:/app-status:rw"               # status files (e.g. file.downloaded)
    - "${REPO_DIR}/osm-to-pgsql:/osm-to-pgsql:ro"  # osm2pgsql script
    - "${OSM_PGSQL_DATA_DIR}:/osm-pgsql:rw"        # nodes.cache storage
    environment:
      FLAG_PG_IMPORTED: "/app-status/osm-pgsql.imported"
      IS_FULL_PLANET: "${IS_FULL_PLANET}"
      LOOP_SLEEP: 60
      OSM_PGSQL_CODE: "/osm-to-pgsql"
      OSM_PGSQL_CPU_UPDATE: 2
      OSM_PGSQL_DATA: "/osm-pgsql"
      OSM_PGSQL_MEM_UPDATE: "${MEM_OSM_PGSQL_UPDATE_MB}"
      POSTGRES_DB: gis
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD:
      POSTGRES_USER: sophox
    networks:
    - postgres_net
    logging:
      driver: json-file
      options: {max-file: "3", max-size: "10m"}

networks:
  postgres_net:
